<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Article Management' => '文章管理',
  'Category Management' => '分类管理',
  'Comment Management' => '评论管理',
  'Home' => '首页',
  'administrator' => '管理员',
  'anonymous user' => '匿名用户',
  'authenticated user' => '认证用户',
  'Abstract length' => '摘要长度',
  'Account List' => '账号列表',
  'Account Management' => '账号管理',
  'Allow registration' => '允许注册',
  'Auto abstract generation' => '自动生成摘要',
  'Back To Front' => '返回前台',
  'Cancel' => '取消',
  'Category List' => '分类列表',
  'Comment page size' => '评论分页大小',
  'Content' => '内容',
  'Content setting' => '内容设置',
  'Create Account' => '创建账号',
  'Create Role' => '创建角色',
  'Create role success' => '创建角色成功',
  'Default country' => '默认国家',
  'Default language' => '默认语言',
  'Default time zone' => '默认时区',
  'Delete' => '删除',
  'Delete Role' => '删除角色',
  'Email address' => '邮件地址',
  'Email address is not valid' => '邮件地址不合法',
  'Git base path' => 'Git基准目录',
  'Git setting' => 'Git设置',
  'Localization setting' => '本地化设置',
  'Member' => '成员',
  'Modify Account' => '修改账号',
  'Modify Role' => '修改角色',
  'No' => '否',
  'Off' => '关闭',
  'On' => '开启',
  'Permission Management' => '权限管理',
  'Permission management' => '权限管理',
  'Permission saved success' => '权限保存成功',
  'Post page size' => '文章分页大小',
  'Reset' => '重置',
  'Role changed success' => '角色修改成功',
  'Role deleted success' => '角色删除成功',
  'Role description' => '角色描述',
  'Role name' => '角色名',
  'Roles List' => '角色列表',
  'Roles Management' => '角色管理',
  'Save' => '保存',
  'Save configuration' => '保存配置',
  'Save configuration failed' => '保存配置失败',
  'Save configuration success' => '保存配置成功',
  'Site description' => '站点描述',
  'Site information' => '站点信息',
  'Site name' => '站点名称',
  'Slogan' => '口号',
  'Submit' => '提交',
  'System' => '系统',
  'The role is existed' => '该角色已存在',
  'Yes' => '是',
  'category_id::Category ID' => 'category_id::分类ID',
  'description::Description' => 'description::描述',
  'name::Category Name' => 'name::分类名',
  'name::Permission Name' => 'name::权限名称',
  'name::Role name' => 'name::角色名称',
);
