<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About Author' => '关于作者',
  'About Tag' => '关于标签',
  'All' => '全部',
  'Article' => '文章',
  'Avatar' => '头像',
  'Comment' => '评论',
  'Comment to me:' => '评论我的：',
  'Comment to {author}:' => '给{author}的评论：',
  'Comments' => '评论列表',
  'Comments received' => '收到的评论',
  'Comments sent' => '发出的评论',
  'Content' => '内容',
  'Contributors' => '贡献者',
  'Create Post' => '创建文件',
  'Female' => '女',
  'Forgot password?' => '忘记密码？',
  'Login' => '登陆',
  'Male' => '男',
  'Message' => '消息',
  'Outline' => '大纲',
  'Password' => '密码',
  'Post Status' => '文章状态',
  'Profile' => '个人信息',
  'Remember Me' => '记住密码',
  'Reply' => '回复',
  'Reply to me:' => '回复我的：',
  'Reply to {author}:' => '给{author}的回复：',
  'Reset' => '重置',
  'Revision information' => '修订信息',
  'Save' => '保存',
  'Secret' => '保密',
  'Send mail' => '发送邮件',
  'Show outline' => '显示大纲',
  'Sign up' => '注册',
  'Submit' => '提交',
  'Submit ' => '提交',
  'System' => '系统',
  'Topic' => '专题',
  'Updated at {time}' => '更新于 {time}',
  'Upload Avatar' => '上传头像',
  'View All' => '查看全部',
  'View history' => '查看历史',
  'Viewing history version created in {time}.' => '正在查看浏览创建于 {time} 的历史版本',
  'Visit the latest' => '查看最新版本',
  'no description' => '没有描述信息',
  'show all' => '查看全部',
  'tag' => '标签',
  'user' => '用户',
  '{count} posts attached' => '{count}篇文章由此标签',
  '{count} views' => '{count}人浏览',
  'Articles' => '文章',
  'Home' => '首页',
  'Logout' => '退出',
  'My Account<b class="caret"></b>' => '我的账号<b class="caret"></b>',
  'Sign In' => '登陆',
  'Sign Up' => '注册',
  'Topics' => '专题',
);
