#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
basedir="/var/lib/openshift/48679206294f439a9bb29683cdb2c7a1/app-root/runtime/repo/"

cd $basedir

dirs="assets css images js protected themes index.php"
dist="php/"
for dir in $dirs 
do
	cp $dir $dist -rf
done

cd $dist

chmod 777 assets
sed 's#/../#/../../#' index.php -i
sed 's/localhost/127.6.173.1/' protected/config/main.php -i

mkdir protected/runtime
